#!/bin/bash

# Check if PYFILE environment variable is set
if [ -z "$PYFILE" ]; then
    echo "Error: PYFILE environment variable is not set."
    exit 1
fi


if [ ! -f "$PYFILE" ]; then
    echo "Error: File specified in PYFILE environment variable does not exist."
    exit 1
fi


python3 "$PYFILE"

if [ $? -ne 0 ]; then
    echo "Error: Python script failed to execute."
    exit 1
fi

exit 0
